export const config = state => state.config
export const isLogin = state => state.isLogin
export const user = state => state.user
export const custom = state => state.custom
export const conversationList = state => state.conversationList
export const conversationUserList = state => state.conversationUserList
export const isConnect = state => state.isConnect
export const connectype = state => state.connectype
export const call = state => state.call
export const telephone = state => state.telephone
export const appointmentNum = state => state.appointmentNum
export const homeUnfinishWork = state => state.homeUnfinishWork
